services:
  postgres:
    build: ./postgresdb/
    image: db
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: nodes
    ports:
      - "5001:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgresdb/config:/config
      - ./postgresdb/archive:/mnt/server/archive
    command: -c config_file=/config/postgresql.conf

volumes:
  pgdata: