services:
  postgres:
    build: ./postgresdb/
    image: db
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: nodesdb
    ports:
      - "5000:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgresdb/config:/config
      - ./postgresdb/archive:/mnt/server/archive
    command: -c config_file=/config/postgresql.conf
  server:
    build: ./
    container_name: server
    image: server
    ports:
      - "3000:3000"
volumes:
  pgdata: